export enum AssignmentCategory {
  CORE = "CORE",
  TEACHER_ASSIGNED = "TEACHER_ASSIGNED",
  AI = "AI",
  ROLLOVER = "ROLLOVER",
  PREREQUISITE = "PREREQUISITE"
}

export enum AssignmentSequence {
  CONTINUE = "CONTINUE", // CONTINUE THROUGH TO NEXT ACTIVITY (DEFAULT)
  BREAK = "BREAK", // ACTIVITY THAT BREAKS OUT BACK TO MENU
}

export enum AssignmentStatus {
  ASSIGNED = "ASSIGNED",
  UNASSIGNED = "UNASSIGNED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETE = "COMPLETE",
  DONE = "DONE",
  ERROR = "ERROR",
}

export enum AssignmentType {
  CURRICULUM = "CURRICULUM",
  ASSESSMENT = "ASSESSMENT",
  INSTRUCT = "INSTRUCT",
  SKIP_OVERRIDE = "SKIP_OVERRIDE",
}