export enum StatusType {
  COMPLETE = "COMPLETE",
  SCHEDULED = "ASSIGNED",
  ACTION_NEEDED = "ACTION_NEEDED",
  UNDER_REVIEW = "UNDER_REVIEW",
  IN_PROGRESS = "IN_PROGRESS",
  UNASSESSED = "UNASSESSED",
}